// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3_Pzasmc5s0DE3ZMj5NhJkRPrJ4XDuig',
    appId: '1:761866217617:web:e8c5b5f124d363fe9f7730',
    messagingSenderId: '761866217617',
    projectId: 'autogestion-pro',
    authDomain: 'autogestion-pro.firebaseapp.com',
    storageBucket: 'autogestion-pro.firebasestorage.app',
    measurementId: 'G-BMYFHJH22R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJK-0cDkVg5320IN1b7AZQ9GhqfXLWREo',
    appId: '1:221437183793:android:04004fc2b44042b3acd210',
    messagingSenderId: '221437183793',
    projectId: 'autogestion-max',
    storageBucket: 'autogestion-max.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdyau4Mn0DKQFWvw9NA5_KNIVImHouohM',
    appId: '1:761866217617:ios:351b95ef153f5ad19f7730',
    messagingSenderId: '761866217617',
    projectId: 'autogestion-pro',
    storageBucket: 'autogestion-pro.firebasestorage.app',
    iosBundleId: 'com.example.autogestionPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdyau4Mn0DKQFWvw9NA5_KNIVImHouohM',
    appId: '1:761866217617:ios:351b95ef153f5ad19f7730',
    messagingSenderId: '761866217617',
    projectId: 'autogestion-pro',
    storageBucket: 'autogestion-pro.firebasestorage.app',
    iosBundleId: 'com.example.autogestionPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3_Pzasmc5s0DE3ZMj5NhJkRPrJ4XDuig',
    appId: '1:761866217617:web:6f67b16b8adbb2119f7730',
    messagingSenderId: '761866217617',
    projectId: 'autogestion-pro',
    authDomain: 'autogestion-pro.firebaseapp.com',
    storageBucket: 'autogestion-pro.firebasestorage.app',
    measurementId: 'G-Y3T0NTPBQY',
  );
}
